sudo: true
dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      -
env:
  secure: Bjd9TGXEGcMp+eSjhO+y1dFB597k53rsc7LnsETOS4peaN893IQAWBu5dRT5Jlk2HGM3xTArDCkRNKmNArrrDgK4Y4K6/H+g0reCvsawlUYnhRjf8u7J3IkuE9S4taixCdkcelOLcJml0dY7iM1XQJtzbABDvRaOXke0k/DrQhyre4R0TPHVm/3d7ETINYwlSend6iWPK9AzB28jRIs96/dVZlmtLcPtApQKD5u+xhYPvQSy+t5ylbxSqdpaQ6cYX2ySFjpK3HsYZG2OHAIC0cCDJMO/7pvlup9E5c6YfnKJEQQT/lFuLr6X87RuAXFl8IsSUhh2/yFU0GjKxBL312N/zynPdjKiEY9Egv3/yirRq4td4wb5zAlBvghiRnXFWYn/DN38gXDSFnhJr6xK/mS51/loGDARJuVZk3j6FjplzD9xE8yaq35O8OMvQDN/WsvAiW25X/Tt/4Y5Id6qpCCYwMDLWCcCFTMiuVdPt4b8dIF1X+7R3kYBQSoMDTIGHTlljzz76a8FErh1qnzJ0GN74FIVOY8WleaFlNfj8iP8BrGutr8apFDffcuhwnFTdw6IsNYkZiswOhGfse2Yj+aNSDYaAxF1XK7+WdGZks7XyejP/jHjOn/iLbJvnkENLcD1SQIcNCTXFhwEGxuoiVS3YxPdsp4gUgawMe/ufYs=

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pip install --user cpp-coveralls
  -
script:
  - g++ -v && cmake --version
  - gcov -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCOVERALLS=ON
  - cmake --build .
  - "./tests/tests [implemented]"
after_success:
  - ls
  - cd ..
  - |
    coveralls --build-root build --gcov-options '\-lp' \
     -e build/src/lib \
     -e build/CMakeFiles \
     -e build/CMakeFiles/feature_tests.c \
     -e build/CMakeFiles/feature_tests.cxx \
     -e src/lib \
     -e tests \
     -E ".*CMakeFiles.*" \
     -E ".*lib.*"
  - curl -o /tmp/travis-automerge https://raw.githubusercontent.com/kappatych/travis-automerge/master/travis-automerge
  - chmod a+x /tmp/travis-automerge
  - BRANCHES_TO_MERGE_REGEX='^f.*' BRANCH_TO_MERGE_INTO=dev GITHUB_REPO=kappatych/ci_test
    /tmp/travis-automerge
