sudo: true
dist: xenial
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

env:
  - secure: "0BiU3csFt1eKre754LtUdM4NmN2nqYc34F/a7XGzFXzP3sn8USfhq4elnOQDtSlDcfGFKEBrls06I2ytK88W41GBYNqZQITBIukOHS5cRbWFM2xeEMbgRDv+L1ynQWSqAAYR+76NxSxU2h4dLz7YN95WQev2aH396QCWXf/e0X4M0gjsdBUT6ZtsVYfI7h1FERY92Dkf9ShGkhplZeCkiHvBU2VQwO2E5pKlNp/SJp28ERXcgIGEI880/tAGoDqxAuco+ZIiqsq9Zni7r/ucBVoDRr2O6vF5hklhIfHl+/wIbY5Y8hgZB9nziyqJ4Vi27G8KnZufCCRvMY39KP9X6wmX5TjeFqRDhmWDFd1RWJ22ichr0Jx0zOGHwY5wrH/6OC48ukqH002u7QvzzGoMIPREw8W+5CjF8qTUbiybI73ie9ZIWaseGBeA+c0x6JNuoP89d2QOM818yT2I/hsFRhs4V/tkQfd3uROCxpsv+VOehF6zyXcVLyf2HvNZBQbrrR0qpm0hNnn3ApWSFntKStUZceZmiPjhKABgVpOfkZd/2u7WMbR7vfm2G2/bH/uJeMvbVMqMVrulA7hAMgLlmbi0S8F2j68j+NQjDH0EjOI/xp+1f0stz2fU5ewxIgs8S/V+Ue9EYrSPrMS21e16toBzyYCLoVk85/FUrxJcxrw="

matrix:
  fast_finish: true

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pip install --user cpp-coveralls

script:
  - g++ -v && cmake --version
  - gcov -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCOVERALLS=ON
  - cmake --build .
  - "./tests/tests [implemented]"
after_success:
  - ls
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $GITHUB_SECRET_TOKEN
  - cd ..
  - |
    coveralls --build-root build --gcov-options '\-lp' \
     -e build/src/lib \
     -e build/CMakeFiles \
     -e build/CMakeFiles/feature_tests.c \
     -e build/CMakeFiles/feature_tests.cxx \
     -e src/lib \
     -e tests \
     -E ".*CMakeFiles.*" \
     -E ".*lib.*"
  - curl -o /tmp/travis-automerge https://raw.githubusercontent.com/kappatych/travis-automerge/master/travis-automerge
  - chmod a+x /tmp/travis-automerge
  - BRANCHES_TO_MERGE_REGEX='^f.*' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=kappatych/ci_test /tmp/travis-automerge
